In [1]:
# Train test split.

In [2]:
import pandas as pd

In [3]:
df = pd.read_csv('./homeprices_encoding_l6.csv')

In [4]:
df.head()

              town  area   price
0  monroe township  2600  550000
1  monroe township  3000  565000
2  monroe township  3200  610000
3  monroe township  3600  680000
4  monroe township  4000  725000

In [8]:
x = df.drop(['price'], axis='columns')
x

               town  area
0   monroe township  2600
1   monroe township  3000
2   monroe township  3200
3   monroe township  3600
4   monroe township  4000
5      west windsor  2600
6      west windsor  2800
7      west windsor  3300
8      west windsor  3600
9       robinsville  2600
10      robinsville  2900
11      robinsville  3100
12      robinsville  3600

In [10]:
y = df.price
y

0     550000
1     565000
2     610000
3     680000
4     725000
5     585000
6     615000
7     650000
8     710000
9     575000
10    600000
11    620000
12    695000
Name: price, dtype: int64

In [5]:
from sklearn.model_selection import train_test_split

In [11]:
X_train, X_test, y_train, y_test = train_test_split(x, y, test_size=0.2, random_state=42)

In [12]:
X_train

               town  area
8      west windsor  3600
5      west windsor  2600
2   monroe township  3200
1   monroe township  3000
12      robinsville  3600
4   monroe township  4000
7      west windsor  3300
10      robinsville  2900
3   monroe township  3600
6      west windsor  2800

In [13]:
X_test

               town  area
11      robinsville  3100
9       robinsville  2600
0   monroe township  2600

In [14]:
y_train

8     710000
5     585000
2     610000
1     565000
12    695000
4     725000
7     650000
10    600000
3     680000
6     615000
Name: price, dtype: int64

In [15]:
y_test

11    620000
9     575000
0     550000
Name: price, dtype: int64