In [1]:
# One-Hot encoding.

In [2]:
import pandas as pd

In [3]:
df = pd.read_csv('./homeprices_encoding_l6.csv')

In [5]:
df

               town  area   price
0   monroe township  2600  550000
1   monroe township  3000  565000
2   monroe township  3200  610000
3   monroe township  3600  680000
4   monroe township  4000  725000
5      west windsor  2600  585000
6      west windsor  2800  615000
7      west windsor  3300  650000
8      west windsor  3600  710000
9       robinsville  2600  575000
10      robinsville  2900  600000
11      robinsville  3100  620000
12      robinsville  3600  695000

In [6]:
dummies = pd.get_dummies(df.town, dtype='int')

In [7]:
dummies

    monroe township  robinsville  west windsor
0                 1            0             0
1                 1            0             0
2                 1            0             0
3                 1            0             0
4                 1            0             0
5                 0            0             1
6                 0            0             1
7                 0            0             1
8                 0            0             1
9                 0            1             0
10                0            1             0
11                0            1             0
12                0            1             0

In [10]:
merged = pd.concat([df, dummies], axis='columns')

In [11]:
merged

               town  area   price  monroe township  robinsville  west windsor
0   monroe township  2600  550000                1            0             0
1   monroe township  3000  565000                1            0             0
2   monroe township  3200  610000                1            0             0
3   monroe township  3600  680000                1            0             0
4   monroe township  4000  725000                1            0             0
5      west windsor  2600  585000                0            0             1
6      west windsor  2800  615000                0            0             1
7      west windsor  3300  650000                0            0             1
8      west windsor  3600  710000                0            0             1
9       robinsville  2600  575000                0            1             0
10      robinsville  2900  600000                0            1             0
11      robinsville  3100  620000                0            1             0
12      robinsville  3600  695000                0            1             0

In [16]:
new_df = merged.drop(['town'], axis='columns')

In [17]:
new_df

    area   price  monroe township  robinsville  west windsor
0   2600  550000                1            0             0
1   3000  565000                1            0             0
2   3200  610000                1            0             0
3   3600  680000                1            0             0
4   4000  725000                1            0             0
5   2600  585000                0            0             1
6   2800  615000                0            0             1
7   3300  650000                0            0             1
8   3600  710000                0            0             1
9   2600  575000                0            1             0
10  2900  600000                0            1             0
11  3100  620000                0            1             0
12  3600  695000                0            1             0

In [20]:
# We need to drop one of the dummy variables, to avoid dummy variable trap.
final_df = new_df.drop(['robinsville'], axis='columns')

In [21]:
final_df

    area   price  monroe township  west windsor
0   2600  550000                1             0
1   3000  565000                1             0
2   3200  610000                1             0
3   3600  680000                1             0
4   4000  725000                1             0
5   2600  585000                0             1
6   2800  615000                0             1
7   3300  650000                0             1
8   3600  710000                0             1
9   2600  575000                0             0
10  2900  600000                0             0
11  3100  620000                0             0
12  3600  695000                0             0

In [26]:
x = final_df.drop(['price'], axis='columns')

In [27]:
x

    area  monroe township  west windsor
0   2600                1             0
1   3000                1             0
2   3200                1             0
3   3600                1             0
4   4000                1             0
5   2600                0             1
6   2800                0             1
7   3300                0             1
8   3600                0             1
9   2600                0             0
10  2900                0             0
11  3100                0             0
12  3600                0             0

In [28]:
y = final_df.price

In [29]:
y

0     550000
1     565000
2     610000
3     680000
4     725000
5     585000
6     615000
7     650000
8     710000
9     575000
10    600000
11    620000
12    695000
Name: price, dtype: int64

In [30]:
from sklearn.linear_model import LinearRegression

In [31]:
model = LinearRegression()

In [32]:
model.fit(x,y)

LinearRegression()

In [33]:
import joblib

In [34]:
joblib.dump(model, 'mlr_encoded')

['mlr_encoded']